sudo: required
lenguage: java
jdk:
- oraclejdk8
- openjdk8
notifications:
  email:
    recipients:
      - one@example.com
    on_success: change
    on_failure: change
    
script:
- mvn clean package
